depromeet/layer

- .github/workflows/build-test.yml
> ### Build 자동화 workflow 추가
---
- main 브랜치에 push, pull request 시 자동 빌드
- 테스트 진행을 못해봤는데, 머지 후 따로 확인해보겠습니다 🧐
- #1 
-
> chore/#1/build 자동화 workflow

- package.json
> ### SNAPSHOT 추가
---
- package.json 버전 명시를 위한 snapshot 추가
- `package.json`
- #1 
- 버전 명시를 위한 수정을 진행했어요
- 프로젝트 이름이 잘못 명시되어있어서 변경했어요
> chore: #1 modify package.json version (snapshot)

- .github/workflows/build-test.yml
> 빌드 워크플로우 수정
---
- develop 브랜치 추가
- pull_request_target -> pull_request 원복 ([pull_request_target은 기준 브랜치로 도는](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) 이슈)
-
-
-
> chore: #1 build workflow develop 추가, pull_request_target 원복

- .github/workflows/workflow-dev.yml
> ### 개발 서버 환경을 위한 새로운 워크플로우 추가
---
- 개발 서버 운영을 위해 새로운 워크플로우를 추가했어요
- .github/workflows/workflow-dev.yml
-
- https://layer-dev.vercel.app/
> 개발 서버 환경을 위한 새로운 워크플로우 추가

- .github/workflows/auto-review-assign.yml
- .github/workflows/workflow-dev.yml
> ### 워크플로우 추가를 위한 메인 병합
---
- 워크플로우 추가를 위한 메인 병합
- .github/workflows/auto-review-assign.yml
-
-
> 워크플로우 추가를 위한 메인 병합

- src/app/test/Staging.tsx
- src/component/ProgressBar/ProgressBar.tsx
- src/router/index.tsx
- src/style/global.css
- vercel.json
> ### 공통 컴포넌트 프로그래스 바 개발
---
- 공통 컴포넌트 프로그래스 바 개발
- 공통 컴포넌트 프로그래스 바 개발
- src/app/test/Staging.tsx
- src/component/ProgressBar/ProgressBar.tsx
- 해당 컴포넌트는 현재 페이지인 `curPage`와 `lastPage`를 props로 받고 있어요, 
현재 페이지에 따라 프로그래스 바가 올라가는 형태로 제공이 되고 있습니다.
```jsx
const [page, setPage] = useState(0);
/** 변경되는 page 상태 값에 따라 프로그래스 파란색 바가 올라감 */
<ProgressBar curPage={page} lastPage={10}/>
```
- 개발 환경에서 디자이너분들도 디자인 하시면서 직접 체험해보시면 좋을 것 같다는 생각이 들어서 
프로그래스 바를 체험할 수 있는 예제 페이지를 임시로 만들어보았어요
- 해당 페이지는 공유 후 삭제될 페이지입니다!
https://github.com/depromeet/layer/assets/19422885/0a065128-6894-41e7-b95a-95fb792032bb
> 공통 컴포넌트 프로그래스 바 개발

- src/component/common/button/ButtonProvider.tsx
> ### 버튼 컴포넌트 수평 · 수직 정렬 기능 제공
---
- 기존 디자인 변경에 따라 버튼 프로바이더(컴파운드) 컴포넌트에 정렬 기능을 제공합니다.
- src/component/common/button/ButtonProvider.tsx
- #11
- 사용 방법은 아래와 같습니다.
```jsx
/** 정렬의 기본 값은 `vertical` 입니다. */
<ButtonProvider sort="horizontal">
<Button colorSchema="primary">테스트</Button>
<Button colorSchema="sky">테스트</Button>
</ButtonProvider>
```
> 버튼 컴포넌트 수평 · 수직 정렬 기능 제공

- src/component/common/tip/TipBox.tsx
- src/component/common/tip/TipCard.tsx
- src/style/variable.ts
> ### TipCard 컴포넌트 작성
---
- 회고 생성, 스페이스 생성에 사용
- src/component/common/tip/TipCard.tsx
- src/style/variable.ts
- #11 
- 사용방법
```tsx
<TipCard message="회고 설명 또는 진행 목표에 대해 적어도 좋아요 :)" />
```
> TipCard 컴포넌트 작성

- src/component/common/Spacing/Spacing.tsx
- src/component/common/Spacing/index.ts
> ### Space Component 개발
---
- 간격 설정을 위한 Space Component 개발
- src/component/common/Spacing
-
-
> Spacing component 추가

- package.json
- src/api/index.ts
- src/api/login/index.ts
- src/app/login/KakaoLoginRedirection.tsx
- src/app/login/LoginPage.tsx
- src/app/login/SetNicknamePage.tsx
- src/layout/RequireLoginLayout.tsx
- src/router/index.tsx
- src/store/auth/authAtom.tsx
- src/types/loginType/index.tsx
> ### Kakao Login Logic 생성
---
- 카카오 로그인을 생성하였습니다. 
- src/api/login/index.ts
- src/app/login/KakaoLoginRedirection.tsx
- src/app/login/LoginPage.tsx
- src/router/index.tsx
- src/types/loginType/index.tsx
- #35 
- 소셜 로그인을 처음해서 좀 많이 복잡하게 개발한것 같습니다.. 보시고 따끔한 조언 부탁드립니다.. 😢😢 ( 벽 느끼는중...)
> Kakao Login Logic 생성

- src/app.tsx
- src/app/retrospectCreate/RetrospectCreate.tsx
- src/component/retrospectCreate/customTemplate/AddQuestionsBottomSheet.tsx
- src/component/retrospectCreate/customTemplate/EditQuestions.tsx
- src/store/retrospect/retrospectCreate.ts
- src/types/retrospectCreate/index.ts
> ### 회고 생성 시 필수질문 앞에 오도록
---
- 필수질문을 뒤에 붙였음 -> 앞으로 오도록 수정
-
-
-
> fix: #35 회고 생성 시 필수질문 앞에 오도록

- src/app/space/CreateNextPage.tsx
- src/router/index.tsx
> ### 스페이스 아이디 history state 형태 수정
---
-
-
-
-
> 스페이스 아이디 history state 형태 안 맞는 문제 해결

- src/app/login/KakaoLoginRedirection.tsx
> ### 카카오 점프페이지 오류 수정
---
- 카카오 점프페이지 오류 수정
- 커밋 내용 참조
- #35 
-
> 카카오 점프페이지 오류 수정

- src/app/space/CreateDonePage.tsx
- src/app/space/CreateNextPage.tsx
- src/component/space/create/CreateSpace.tsx
> ### 스페이스 생성 뒤로가기 이슈 해결
---
- 스페이스 생성 완료 페이지에서 뒤로 가기가 정상적으로 작동되지 않는 에러 해결
- src/component/space/create/CreateSpace.tsx
- src/app/space/CreateDonePage.tsx
- src/app/space/CreateNextPage.tsx
- #35 
-
> 스페이스 생성 뒤로가기 이슈 해결

- src/component/common/Portal/Portal.tsx
> ### 리액트 포탈 스크롤 공통 로직 수정
---
- 리액트 포탈 스크롤 공통 로직 수정
- (해커톤) 커밋 내용 참조
- #35 
-
> 리액트 포탈 스크롤 공통 로직 수정

- src/app/retrospectCreate/RetrospectCreate.tsx
- src/component/common/button/ButtonProvider.tsx
- src/component/common/radioButton/RadioButtonGroup.tsx
- src/component/retrospectCreate/steps/DueDate.tsx
> ### 타임피커 스크롤 문제 수정
---
- 타임피커 스크롤 문제 수정
-
-
-
> 타임피커 스크롤 문제 수정

- .github/workflows/workflow-dev.yml
- package.json
- pnpm-lock.yaml
- public/robots.txt
- vite.config.ts
> ### SEO를 위한 sitemap · robots.txt 추가
---
- SEO를 위한 sitemap · robots.txt 추가
- vite.config.ts
- public/robots.txt
- package.json
- #83 
-
> SEO를 위한 sitemap · robots.txt 추가

- pnpm-lock.yaml
- src/app/login/SetNicknamePage.tsx
> ### pnpm 에러 처리
---
- pnpm 에러 처리
- 
- #93 
-
> pnpm 에러 처리

- src/style/global.css
> ### 사파리 환경에서 스크롤을 통해 새로고침되는 현상 수정
---
- 사파리 환경에서 스크롤을 통해 새로고침되는 현상 수정했어요.
- src/style/global.css
- #75 
- 스크롤 체이닝이 궁금한다면? : https://junghyeonsu.com/posts/overscroll-behavior/
> 사파리 환경에서 스크롤을 통해 새로고침되는 현상 수정

- src/app/retrospectCreate/RetrospectCreate.tsx
- src/component/retrospectCreate/customTemplate/ConfirmDefaultTemplate.tsx
- src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
- src/component/retrospectCreate/steps/DueDate.tsx
- src/component/retrospectCreate/steps/MainInfo.tsx
- src/component/retrospectCreate/steps/Start.tsx
> ### 회고 생성 레이아웃 수정
---
- 회고 생성 레이아웃을 수정해 스크롤이 정상적으로 작동하도록 수정했습니다.
-
- #96 
-
> 회고 생성 스크롤 문제 수정

- src/component/common/input/Input.tsx
- src/hooks/useValidation.ts
> ### Input 에러 메시지 maxLength 조건 수정
---
- validations props를 전달하지 않아도 maxLength 관련 메시지 뜨도록 수정
- 에러메시지 영역 차지하지 않고 input 아래 뜨도록 수정
- src/component/common/input/Input.tsx
- src/hooks/useValidation.ts
- #88
-
> Input 에러 메시지 maxLength 조건 수정

- src/component/home/NavigaionBar.tsx
> ### 내비게이션 바 색깔 적용
---
- 내비게이션 바 색깔 적용되도록 코드를 수정했습니다. 
- src/component/home/NavigaionBar.tsx
- #115 
-
> fix: #115 내베게이션 바 색깔 수정

- src/app/space/CreateDonePage.tsx
- src/app/space/CreateSpacePage.tsx
- src/hooks/api/auth/useApiGetUser.ts
> ### animation 수정 및 getUser api hook 추가
---
- animation duration 1초로 수정
- getUser api hook 추가
- src/app/space/CreateDonePage.tsx
- src/hooks/api/auth/useApiGetUser.ts
- #35 
-
> animation 수정 및 getUser api hook 추가

- src/hooks/api/space/useApiJoinSpace.ts
> ### 이미 초대받은 경우 토스트 메세지 추가---
- 이미 초대 받은 사람인 경우 토스트 메세지 보여주기
- src/hooks/api/space/useApiJoinSpace.ts
- #35 
-
> 이미 초대받은 경우 토스트 메세지 추가

- src/component/space/join/JoinSpace.tsx
> ### 팀 초대 페이지 팀 이름 데이터 사용
---
- 팀 초대 페이지 팀 이름 데이터 사용
-
-
-
> 팀 초대 페이지 팀 이름 데이터 사용

- src/component/common/button/ButtonProvider.tsx
- src/component/space/view/RetrospectBox.tsx
- src/component/space/view/RetrospectButton.tsx
- src/layout/DefaultLayout.tsx
> ### 스페이스 수정 버튼 및 버튼 스타일 수정
---
- 스페이스 수정 버튼 및 버튼 스타일 수정을 진행했어요
- 커밋 내용을 참고해주세요
- #118 
-
> 스페이스 수정 버튼 및 버튼 스타일 수정

- src/app/home/GoalViewPage.tsx
- src/component/common/tabs/Tabs.tsx
> ### Tabs 컴포넌트 배경 부모 색 적용
---
- Tabs 컴포넌트 배경 부모 색 적용
- 부모 Layout의 --parent-bg-color 변수를 사용합니다.
-
- #129
-
> Tabs 컴포넌트 배경 부모 색 적용

- src/component/write/phase/Write.tsx
> ### 변경 사항이 있을 때만 임시 저장 모달 노출
---
- 변경 사항이 있을 때만 임시 저장 모달 노출할 수 있도록 로직을 설계했어요.
- src/component/write/phase/Write.tsx
- #91 
-
> 변경 사항이 있을 때만 임시 저장 모달 노출

- src/app/template/TemplatePage.tsx
- src/hooks/api/template/useGetTemplateInfo.ts
> ### 템플릿 상세 페이지 데이터 패칭
---
- 템플릿 상세 페이지 데이터 패칭을 진행했어요
- src/app/template/TemplatePage.tsx
- src/hooks/api/template/useGetTemplateInfo.ts
- #35 
- 존재하지 않는 템플릿 아이디를 통해 조회 에러가 발생했을 경우에는 추후 공통 에러 처리에서 처리될 예정이에요.
- 템플릿 별로 테스트를 진행했는데 데이터들이 다 잘 들어오나, 태그의 경우 서버 데이터가 아직 만들어지지 않아 해당 부분은 추가 할 예정이에요.
```
/**
* template
* - 10000 : KPT
* - 10001 : 5F
* - 10002 : Mad Sad Glad
* - 10003 : SSC
* - 10004 : PMI
* - 10005 : 무제
* */
//const templateSet = [10000, 10001, 10002, 10003, 10004, 10005];
```
> 템플릿 상세 페이지 데이터 패칭

- src/component/space/join/JoinSpace.tsx
- src/hooks/api/space/useApiGetSpace.ts
> ### 스페이스 초대 뷰 리더 이름 추가
---
- 스페이스 초대 뷰 리더 이름 추가
- src/component/space/join/JoinSpace.tsx
- #35 
-
> 스페이스 초대 뷰 리더 이름 추가

- pnpm-lock.yaml
- src/app/retrospect/template/list/TemplateListPage.tsx
- src/app/space/SpaceViewPage.tsx
- src/component/common/dateTimePicker/DateTimePicker.tsx
- src/component/common/input/DateTimeInput.tsx
- src/component/common/radioButton/Radio.tsx
- src/component/retrospect/template/list/CustomTemplateListItem.tsx
- src/component/space/view/RetrospectBox.tsx
- src/component/space/view/RetrospectEditModal.tsx
- src/component/space/view/RetrospectOptions.tsx
- src/hooks/api/retrospect/edit/usePatchRetrospect.ts
- src/hooks/api/retrospect/useApiOptionsGetRetrospects.ts
- src/hooks/useDateTimePicker.ts
- src/hooks/useRadioButton.ts
- src/hooks/useRequiredParams.ts
- src/utils/formatDate.ts
> ### 회고 수정 및 삭제
---
- 회고 수정
- 회고 삭제의 경우 이미 연동이 되어 있어 모달만 추가했습니다.
- path parameter를 defined string 타입으로 사용하기 위해 `useRequiredParams` 훅 작성 ([react route 이슈 참고](https://github.com/remix-run/react-router/issues/8498))
- 추가로 DateTimeInput에 defaultValue를 전달할 수 있도록 수정했습니다.
-
- #139 #88
-
> 회고 수정 및 삭제

- src/app/space/SpaceViewPage.tsx
- src/component/space/view/ActionItemListView.tsx
- src/types/spaceType/index.ts
> ### 액션 아이템 더보기 버튼
---
-
-
-
-
> 액션 아이템 더보기 버튼

- src/style/common/animation.ts
> ###Fade In, Out animation 수정
---
- FADE IN : translate 삭제
- FADE IN : to translate 추가
- src/style/common/animation.ts
- #88 
-
> Fade In, Out animation 수정

- src/app/retrospect/analysis/RetrospectAnalysisPage.tsx
- src/app/space/SpaceViewPage.tsx
- src/component/space/view/ActionItemListView.tsx
- src/component/space/view/RetrospectButton.tsx
- src/config/paths.ts
- src/hooks/api/actionItem/useAPiOptionsRecentTeamActionList.ts
- src/router/index.tsx
- src/types/actionItem/index.ts
> ### 회고별 분석 탭 생성 및 스페이스 상세 액션 아이템 수정
---
- 회고별 분석 탭 생성 및 스페이스 상세 액션 아이템 수정
- 커밋 체크 해주세욤
- #156 
-
> 회고별 분석 탭 생성

- src/component/space/view/SpaceCountView.tsx
- src/layout/DualToneLayout.tsx
> ### 템플릿 리스트 페이지 관련 수정사항 반영
---
- 스페이스 상세 페이지의 '대표 템플릿' 클릭 시 템플릿 리스트 페이지로 이동
- DualToneLayout 스크롤 처리
-
- #151 
-
> 템플릿 리스트 페이지 관련 수정사항 반영

- src/app/space/SpaceViewPage.tsx
- src/component/space/view/ActionItemListView.tsx
> ### 스페이스 상세 액션아이템 추가 및 추가 시 상세페이지 반영
---
- 스페이스 상세 액션아이템 추가 및 추가 시 상세페이지 반영하도록 함.
-
- #118 
-
> 스페이스 상세 액션아이템 추가 및 추가 시 상세페이지 반영

- src/hooks/useDateTimePicker.ts
> ### TimePicker 사파리 이슈 해결
---
- 사파리가 ISO형식에 맞는 문자열을 전달하지 않으면 Date를 생성 못하더라구요.
- ISO 형식에 맞게 전달해 유효한 Date 생성하도록 수정했습니다.
-
- #160
-
> TimePicker 사파리 이슈 해결

- src/component/space/view/SpaceAppBarRightComp.tsx
> ### 스페이스 수정 버튼 임시 로직
---
- 내일 QA를 위한 자연스러운 과정을 위해 스페이스 수정시 토스트를 띄우게끔 했어요!!
-
- #118 
-
> 스페이스 수정 버튼 임시 로직

- src/app/retrospectCreate/RetrospectCreate.tsx
> ### 회고 생성 isPending LoadingModal 추가
---
- 회고 생성 POST시 isPending일 경우 LoadingModal을 띄웁니다.
- Write랑 메시지를 통일했어요.
-
- #35
-
> 회고 생성 isPending LoadingModal 추가

- src/app/retrospect/template/list/TemplateListPage.tsx
- src/app/space/SpaceViewPage.tsx
- src/component/space/CreateRetrospectiveSheet.tsx
- src/config/paths.ts
- src/hooks/useDateTimePicker.ts
> ### DateTimePicker 시간 선택 안 한 경우 0시
---
- 시간을 선택하지 않은 경우 undefined 되는 문제 해결
- 시간 선택 안 한 경우 자동으로 0시로 설정
+) 바텀시트에서 템플릿 추천/리스트보기 선택 후 closeBottomSheet를 실행해 navigate 후 다시 페이지로 돌아왔을 때 바텀시트가 닫혀있도록 수정
- src/hooks/useDateTimePicker.ts
- #88
-
> DateTimePicker 시간 선택 안 한 경우 0시

- src/component/common/Toast/ToastItem.tsx
- src/utils/toast/collapseToast.ts
> ### toast z-index 및 애니메이션 수정
---
- 커밋 참조
- toast z-index 및 애니메이션 수정
- #35 
-
> toast z-index 및 애니메이션 수정

- pnpm-lock.yaml
- src/component/space/view/SpaceCountView.tsx
> ### 대표템플릿 태그 이름 출력
---
- 대표템플릿 태그 이름 출력
-
- #118
-
> 대표템플릿 태그 이름 출력

- src/app/template/TemplatePage.tsx
- src/component/home/TagBox.tsx
- src/component/retrospect/template/list/DefaultTemplateListItem.tsx
- src/config/paths.ts
- src/hooks/api/template/useGetTemplateInfo.ts
> ### 템플릿 상세 조회 데이터 패칭 및 로직 추가
---
- 템플릿 상세 조회 데이터 패칭 및 로직 추가를 진행했어요
- 서버에서 추가된 태그 정보를 뷰에 노출되도록 추가했어요
- 커밋 내용을 참조해주세요.
- #35 
-
> 템플릿 상세 조회 데이터 패칭 및 로직 추가

- src/app/space/SpaceViewPage.tsx
- src/app/space/edit/SpaceEditPage.tsx
- src/component/common/ImageUploader/ImageUploader.tsx
- src/component/common/ImageUploader/index.ts
- src/component/space/edit/SpaceEdit.tsx
- src/hooks/api/space/edit/useApiEditSpace.ts
- src/hooks/useInput.ts
- src/router/index.tsx
> ### 스페이스 수정 기능 구현
---
- 스페이스 수정 기능 구현
- ImageUploader 공통 컴포넌트 추가
- edit Space hook 추가
- 커밋 참조
- #35 
- 자잘한 부분들은 계속해서 수정하겠습니다:)
https://github.com/user-attachments/assets/2a506ef3-559e-4f4b-abae-fd68f87bc81b
> 스페이스 수정 기능 구현

- src/app/retrospect/analysis/RetrospectAnalysisPage.tsx
- src/component/retrospect/analysis/PersonalForm.tsx
- src/component/retrospect/analysis/QuestionForm.tsx
- src/component/retrospect/analysis/ResultContainer.tsx
- src/component/retrospect/analysis/ResultControlTab.tsx
- src/component/space/view/RetrospectButton.tsx
- src/component/write/phase/Confirm.tsx
- src/component/write/template/complete/Achievement.tsx
- src/component/write/template/complete/Descriptive.tsx
- src/component/write/template/complete/ResultContainer.tsx
- src/component/write/template/complete/Satisfaction.tsx
- src/config/paths.ts
- src/hooks/api/retrospect/analysis/useGetAnalysisAnswer.ts
- src/router/index.tsx
> ### 회고 분석 중 회고 개인별 · 질문별 조회 페이지 
---
- 회고 분석 중 회고 개인별 · 질문별 조회 페이지 개발을 진행했어요
- 커밋 내용을 참조해주세요!
- #35 
- 최대한 고려하면서 로직을 작성하긴 했는데, 아직 리팩토링 할 요소들이 많이 보이네요 👀
- 리팩토링 요소들은 계속 수정 반영 진행하겠습니다 : )
https://github.com/user-attachments/assets/344344e6-5a5b-4337-bf99-fc22fea75ef1
> 회고 분석 중 회고 개인별 · 질문별 조회 페이지 

- src/router/index.tsx
> ### 잘못된 라우터 수정
---
- 잘못된 라우터 수정을 진행했어요
- 커밋 내용을 참조해주세요
- #35 
-
-
> 잘못된 라우터 수정

- vercel.json
> ### Vercel router 수정
---
- Vercel router 수정을 진행했어요
- vercel.json
-
-
> Vercel router 수정

- src/router/index.tsx
- vercel.json
> fix: vercel router

- src/component/retrospect/template/recommend/Period.tsx
- src/component/retrospect/template/recommend/Purpose.tsx
- src/hooks/api/retrospect/recommend/useApiRecommendTemplate.ts
- src/router/index.tsx
> ### Recommed api hook stableTime 수정
---
- stableTime infinite로 설정하여 최초 1회만 수행
- src/hooks/api/retrospect/recommend/useApiRecommendTemplate.ts
- #35 
-
> Recommed api hook stableTime 수정

- src/component/space/view/RetrospectButton.tsx
- src/layout/EncryptionLayout.tsx
- src/router/index.tsx
> fix: fix router temp

- src/app/login/LoginPage.tsx
> ### 애플 로그인 임시 redirect uri 변경
---
- 애플 로그인 임시 redirect uri 변경
- 
- #137
-
> 애플 로그인 임시 redirect uri 변경

- src/component/space/join/JoinSpace.tsx
- src/hooks/api/space/useApiGetSpace.ts
> ### 초대 화면에서 퍼블릭 정보 요청 API을 하도록 추가 수정
---
- 초대 화면에서 퍼블릭 정보 요청 API을 하도록 추가 수정을 진행했어요
- src/component/space/join/JoinSpace.tsx
- src/hooks/api/space/useApiGetSpace.ts
- #194 
-
> 초대 화면에서 퍼블릭 정보 요청 API을 하도록 추가 수정

- src/app/login/AppleLoginRedirection.tsx
- src/app/login/LoginPage.tsx
- src/router/index.tsx
> ### 애플로그인 리다이렉트 URI 수정
---
- 애플이 리다이렉트 URI가 localhost로 설정이 안돼서 스테이징 도메인으로 설정 후 테스트를 진행합니다.
- https://forums.developer.apple.com/forums/thread/128788
-
- #137
-
> 애플로그인 리다이렉트 URI 수정

- src/app/login/LoginPage.tsx
- src/hooks/api/login/usePostAppleToken.ts
- src/vite-env.d.ts
> ### 애플 로그인 서버 연동
---
- 로컬 환경에서 테스트가 어려워 중간 PR 올립니다.
-
- #137 
-
> 애플 로그인 서버 연동

- src/hooks/api/login/usePostAppleToken.ts
> ### 애플로그인 axios instance로 수정
---
-
-
- #137
-
> 애플로그인 axios instance로 수정

- src/config/paths.ts
- src/hooks/api/login/usePostAppleToken.ts
- src/types/loginType/index.tsx
> ### 애플로그인 신규 회원인 경우 처리
---
-
-
- #137
- 로컬에서 테스트가 어려워 중간 PR 올립니다.
> 애플로그인 신규 회원인 경우 처리

- src/app/login/LoginPage.tsx
- src/app/login/SetNicknamePage.tsx
> ### 애플로그인 토큰 저장
---
-
-
- #137
- 로컬에서 테스트가 어려워 중간 PR 올립니다.
> 애플로그인 토큰 저장

- src/app/home/AnalysisViewPage.tsx
- src/app/home/GoalViewPage.tsx
- src/app/home/RetrospectViewPage.tsx
- src/app/template/TemplatePage.tsx
- src/component/actionItem/ActionItemBox.tsx
- src/component/common/appBar/UserProfileIcon.tsx
- src/component/common/appBar/index.ts
- src/hooks/useCollisionDetection.ts
> ### 스크롤 관련 훅 추가 및 유저 정보 컴포넌트 제작
---
- A와 B가 맞닿을 때를 알려주는 커스텀 훅을 추가했어요, 기존에는 템플릿 종류 상세 페이지에서 활용되고 있었는데 이번 기회에 걷어내는 작업을 했어요
- 유저 정보 컴포넌트가 추상화되어있지 않아서, 공통 컴포넌트로 제작을 했어요
- 커밋 내용을 참고해주세요
- #35
> 스크롤 관련 훅 추가 및 유저 정보 컴포넌트 제작

- .github/workflows/workflow-dev.yml
> ### 실험을 위한 워크플로우 브랜치를 추가합니다.
---
- 실험을 위한 워크플로우 브랜치를 추가합니다.
- .github/workflows/workflow-dev.yml
-
-
> 실험을 위한 워크플로우 브랜치를 추가합니다.

- src/api/server.cjs
> 부분 SSR 테스트

- .github/workflows/workflow-dev.yml
> ### 실험 버셀 배포를 위한 워크플로우 수정
---
- 실험 버셀 배포를 위한 워크플로우 수정
-
-
-
> 실험 버셀 배포를 위한 워크플로우 수정

- vercel.json
> fix vercel.json

- server/server.cjs
> fix: #83 Fix Open Graph Image Url

- src/app/template/TemplatePage.tsx
- src/component/retrospect/template/list/DefaultTemplateListItem.tsx
- src/config/paths.ts
> ### 템플릿 선택 후 경로 수정
---
- 템플릿 선택 후 바로 회고 생성으로 넘어가는 로직 수정
- 선택 후 Recommend Done 페이지로 넘어가도록 수정
- 커밋 확인
- #224 
-
> QA) 템플릿 선택 후 경로 수정

- src/component/space/members/MembersList.tsx
> ### leader일 경우만 팀원 추가 가능 하도록 변경
---
- 팀원 관리 페이지에서 leader일 경우만 팀원 추가 가능 하도록 변경
- 커밋 내용 참조
- #227 
-
> leader일 경우만 팀원 추가 가능 하도록 변경

- src/component/space/edit/SpaceEdit.tsx
> ### 스페이스 수정 이미지 사라지는 현상 해결
---
- 스페이스 수정 시 이미지 변경을 안했을 경우 기존 이미지 적용되도록 수정
- 커밋 참조
- #232 
-
> 스페이스 수정 이미지 사라지는 현상 해결

- pnpm-lock.yaml
- src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
- src/component/retrospectCreate/customTemplate/EditQuestions.tsx
- src/store/retrospect/retrospectCreate.ts
- src/types/retrospectCreate/index.ts
> ### 기본 템플릿에서 커스텀 질문 추가만 한 경우
---
- 기본 템플릿에서 커스텀 질문 추가만 한 경우, 태그는 `기본 템플릿 태그` 그대로 가져갑니다. (CUSTOM 아님!)
- 이를 반영하기 위해 서버에서 필드가 추가되어 해당 사항을 반영했습니다.
-
- #235
-
> 기본 템플릿에서 커스텀 질문 추가만 한 경우

- src/app.tsx
- src/app/login/LoginPage.tsx
- src/app/space/space.const.ts
- src/component/login/SocialLoginArea.tsx
- src/component/login/index.ts
- src/component/space/join/JoinSpace.tsx
- src/hooks/api/login/usePostSignUp.ts
- src/hooks/api/space/useApiJoinSpace.ts
- src/layout/GlobalLayout.tsx
- src/router/index.tsx
> ### 초대장 UX 플로우 개선
---
- 초대장 UX 플로우 개선
- 커밋 내용을 참조해주세요
- #237 
**기존**
- 기존 가입되어있는 혹은 로그인 되어있는 사용자의 경우 `가입되어있는 스페이스입니다` 토스트 메시지 출력 후, 아무 동작을 할 수 없음
- 새로 가입하는 사용자의 경우 메인 홈페이지의 로그인 버튼을 통해 로그인 후, 다시 수락하기 화면에서 버튼을 통해 수락 플로우를 진행
**변경** 
- 기존 가입되어있는 혹은 로그인 되어있는 사용자의 경우 수락한 스페이스로 이동할 수 있도록 플로우 개선
- 새로 가입하는 사용자의 경우 화면 이동에 대한 뎁스를 줄이기 위해 모달을 띄어 한 화면에서 회원가입 및 로그인과, 회원가입 완료 후 바로 해당 스페이스로 이동할 수 있도록 플로우 개선
> 초대장 UX 플로우 개선

- src/component/space/members/MembersItem.tsx
- src/component/space/space.const.ts
> ### 팀원 관리 스페이스 이미지 관련 개선
---
- 팀원 이미지가 없는 경우 default img로 변경
- 이미지가 네모로 보여지는 현상 수정
- 커밋 참조
- #234 
-
> QA) 팀원 관리 스페이스 이미지 관련 개선

- src/component/login/SocialLoginArea.tsx
- src/component/space/view/SpaceCountView.tsx
> ### 애플 로그인 버튼 로딩 반영
---
- 애플 로그인 버튼 로딩 반영을 진행해요
- src/component/login/SocialLoginArea.tsx
- #229 
-
> 애플 로그인 버튼 로딩 반영

- src/utils/space/cryptoKey.ts
> ### 암호화 키 생성 에러 해결
---
- Invalid Array length Error 해결
- 커밋 참조
- #234 
-
> QA) 암호화 키 생성 에러 해결

- src/layout/RequireLoginLayout.tsx
> ### 로그인 리다이렉트 시 토스트 제거
---
- 로그인 리다이렉트 시 토스트 제거
-
- #254 
-
> 로그인 리다이렉트 시 토스트 제거

- src/app/space/CreateSpacePage.tsx
- src/component/space/create/CreateSpace.tsx
- src/component/space/create/Thumb.tsx
- src/component/space/members/MembersItem.tsx
> ### 멤버 이미지 수정 및 스페이스 생성 Loading 적용
---
- 멤버 이미지 수정 
- 스페이스 생성 후 Loading 적용
- 커밋 참조
- #234 
-
> QA) 멤버 이미지 수정 및 스페이스 생성 Loading 적용

- src/component/common/input/Input.tsx
- src/component/common/input/InputLabelContainer.tsx
- src/component/common/input/Label.tsx
- src/component/common/input/TextArea.tsx
- src/component/common/tip/TipCard.tsx
> ### Input, Textarea 디자인 시스템 반영
---
-
-
-
- Textarea height 관련 리팩토링 필요
> Input, Textarea 디자인 시스템 반영

- index.html
- package.json
- pnpm-lock.yaml
- vite.config.ts
> 핫픽스 웹 환경 반영

- index.html
- src/component/actionItem/NotActionItemBoxData.tsx
- src/component/retrospectCreate/customTemplate/EditQuestions.tsx
> ### 초대를 위한 오픈 그래프 수정
---
-
-
-
-
> 초대를 위한 오픈 그래프 수정

- src/app/space/CreateNextPage.tsx
- src/utils/space/cryptoKey.ts
> ### hotfix: 암호화 키 인코딩, 디코딩 로직 추가
---
- hotfix: 암호화 키 인코딩, 디코딩 로직 추가
- 커밋 참조
- #234 
-
> hotfix: 암호화 키 인코딩, 디코딩 로직 추가

- server/server.cjs
> ### 초대 관련 SSR 로직 수정
---
-
-
-
-
> 초대 관련 SSR 로직 수정

- src/app/space/CreateDonePage.tsx
- src/app/space/CreateNextPage.tsx
- src/component/common/ImageUploader/ImageUploader.tsx
- src/component/space/create/CreateSpace.tsx
- src/component/space/create/Thumb.tsx
- src/component/space/space.const.ts
- src/hooks/api/space/useApiPostSpace.ts
> ### hotfix: 이미지 업로드 로직 수정
---
- 업로드 안할 시 null 값 보내도록 처리
- 다음에 하기 버튼 활성화
- 커밋 참조
- #234
-
> hotfix: 이미지 업로드 로직 수정

- package.json
- pnpm-lock.yaml
- src/layout/GlobalLayout.tsx
> ### hotfix: 핫자 적용
---
- 핫자 적용
- 우선 세팅 하고 추가적으로 기능 붙일 예정
- 커밋 참조
- #284 
-
> hotfix: 핫자 적용

- src/component/retrospect/template/recommend/RecommendTemplate.tsx
> ### 템플릿 추천 뒤로가기 로직 수정
---
-  템플릿 추천 뒤로가기 로직 수정
- 커밋 참조
-
-
> hotfix: 템플릿 추천 뒤로가기 로직 수정

- src/component/home/SummaryInsightBox.tsx
- src/component/retrospect/analysis/Analysis.tsx
> ### 분석페이지 관련 버그 수정
---
- 분석페이지 관련 버그 수정 
- 커밋참고
- #299
-
> 분석페이지 관련 버그 수정

- src/component/retrospect/analysis/Analysis.tsx
- src/component/retrospect/template/card/TemplateCard.tsx
- src/layout/DualToneLayout.tsx
> ### 회고 작성하지 않은 사람 개인 분석 조회
---
- 회고 작성하지 않은 사람 개인 분석 조회
-
- #269 
-
> hotfix: 회고 작성하지 않은 사람 개인 분석 조회

- pnpm-lock.yaml
- src/app/retrospect/template/list/TemplateListPage.tsx
- src/app/space/SpaceViewPage.tsx
- src/component/retrospect/template/list/CustomTemplateListItem.tsx
- src/component/space/view/SpaceCountView.tsx
> ### 커스텀 템플릿을 오로지 리더만 관리할 수 있도록 수정
---
- 커스텀 템플릿 수정 및 삭제 메뉴가 리더에게만 보이도록 수정했어요
- 커밋 내역을 참고해주세요
- #269 
-
> 커스텀 템플릿을 오로지 리더만 관리할 수 있도록 수정

- package.json
> Update version 1.0.2 snapshot

- src/component/home/SummaryInsightBox.tsx
> ### 분석 BlueTextBox UI 깨지는 문제 해결
---
- 분석 BlueTextBox UI 깨지는 문제를 해결했어요.
- src/component/home/SummaryInsightBox.tsx
- 
-
> 분석 BlueTextBox UI 깨지는 문제 해결

- src/component/retrospect/template/recommend/RecommendDone.tsx
> ### 회고 생성으로 넘어올 때 spaceId 누락된 부분 수정
---
- 이슈 참고
-
- #317 
-
> 회고 생성으로 넘어올 때 spaceId 누락된 부분 수정

- src/component/login/SocialLoginArea.tsx
> ### 카카오 환경변수명 변경
---
-
-
-
-
> 카카오 환경변수명 변경

- index.html
- src/component/retrospect/template/recommend/RecommendDone.tsx
> ### 도큐먼트 언어 설정을 `한국`으로 변경
---
- 도큐먼트 언어 설정을 `한국`으로 변경을 했어요
- index.html
- #322 
-
> 도큐먼트 언어 설정을 '한국' 으로 변경

- src/component/retrospect/template/recommend/Purpose.tsx
- src/component/space/create/Field.tsx
> ### 멀티 셀렉터 3개 이상 클릭시 토스트 메세지
---
- 멀티 셀렉터 3개 이상 클릭시 토스트 메세지
- 커밋 참조
-  #325 
-
> 멀티 셀렉터 3개 이상 클릭시 토스트 메세지

- src/app/login/SetNicknamePage.tsx
- src/component/common/tip/TipCard.tsx
- src/component/retrospectCreate/steps/MainInfo.tsx
- src/component/space/create/Info.tsx
> ### Input 에러메시지 공간을 위한 간격 조정
---
- 에러메시지가 position absolute로 공간을 차지하지 않기 때문에 Input 바로 아래 다른 요소가 있는 경우 겹쳐 보이는 문제 → 간격 수정
-
- #330 
-
> Input 에러메시지 공간을 위한 간격 조정

- apps/web/src/component/retrospect/template/card/TemplateCard.tsx
> ### 템플릿 카드 사이즈 변경
---
- 템플릿 카드 사이즈 변경
-
- #330 
-
> 템플릿 카드 사이즈 변경

- apps/web/src/component/space/members/MembersList.tsx
> ### 팀원 1명일 때는 편집 버튼 제거
---
- 팀원 1명일 때는 편집 버튼 제거
- 
- #330 
-
> 팀원 1명일 때는 편집 버튼 제거

- apps/mobile/package.json
- apps/web/package.json
- lerna.json
- package.json
- packages/shared/package.json
> v1.0.3-SNAPSHOT

- apps/mobile/package.json
- apps/web/package.json
- lerna.json
- package.json
- packages/shared/package.json
> v1.0.2-SNAPSHOT

- apps/web/src/app/space/SpaceViewPage.tsx
- pnpm-lock.yaml
> ### state 전달하는 네이게이션 웹으로 변경
---
-
-
-
-
> state 전달하는 네이게이션 웹으로 변경

- apps/web/src/component/common/tip/Tooltip.tsx
> ### bottom 툴팁 애니메이션 수정
---
- bottom의 경우 애니메이션이 잘못들어간 내용을 수정했습니다.
-
-
-
> bottom 툴팁 애니메이션 수정

- apps/web/src/layout/DualToneLayout.tsx
> ### 스페이스 상세 화면에서 바닥 여백이 보이는 현상 수정
---
- 스페이스 상세 화면에서 바닥 여백이 보이는 현상 수정을 했어요
- apps/web/src/layout/DualToneLayout.tsx
- #330 
-
> 스페이스 상세 화면에서 바닥 여백이 보이는 현상 수정

- apps/web/src/component/write/phase/Write.tsx
- apps/web/src/component/write/template/write/Descriptive.tsx
- apps/web/src/component/write/template/write/ToolTip.tsx
- apps/web/src/component/write/template/write/index.ts
> ### 사용성 개선 작업 중 작성 화면 글자 수 및 툴팁 반영
---
- 회 작성 화면 글자 수 노출과 툴팁 반영을 했어요 
- 커밋 내용을 참조해주세요
- #330 
- 
https://github.com/user-attachments/assets/39a00392-e411-4396-a02e-cb4dc6f101d6
> 사용성 개선 작업 중 회고 작성 화면 글자 수 및 툴팁 반영

- apps/web/src/app/retrospect/template/recommend/RecommendSearch.tsx
- apps/web/src/app/space/CreateDonePage.tsx
- apps/web/src/component/space/create/CreateSpace.tsx
- apps/web/src/component/space/create/Thumb.tsx
- apps/web/src/component/space/members/MembersList.tsx
- apps/web/src/component/space/view/SpaceCountView.tsx
- apps/web/src/hooks/api/space/useApiUploadImage.ts
- apps/web/src/store/space/spaceAtom.ts
- apps/web/src/types/space.ts
---
- 스페이스 생성시 이미지 업로드 로딩 적용
- 카카오톡 문구 수정
- 스페이스 뷰 '팀원' -> '인원' 으로 문구 변경
- 개인 스페이스 팀원 추가 불가   
- 커밋 참조
- #381 
-
> QA) #381 기능 구현 및 개선

- apps/web/src/app/retrospect/template/recommend/RecommendSearch.tsx
- apps/web/src/utils/retrospect/chooseParticle.ts
> ### 스페이스 이름에 맞는 조사 적용 함수 
---
- 스페이스 이름에 맞는 조사 적용
- 커밋 참조
- #381 
-
> 스페이스 이름에 맞는 조사 적용 함수 

- apps/web/src/component/write/phase/Write.tsx
> ### 회고 작성 중: (작성 => 임시 저장) 텍스트 변경
---
- 회고 작성 중: (작성 => 임시 저장) 텍스트 변경
- apps/web/src/component/write/phase/Write.tsx
- #388 
-
> 회고 작성 중: (작성 => 임시 저장) 텍스트 변경

- apps/web/src/component/write/phase/Write.tsx
> ### 작성 시 스크롤 이상 현상 수정을 했어요
---
- 작성 시 스크롤 이상 현상을 수정했어요
- 기존 plainText를 대응하기 위해 추가해놓았던 스타일 요소가 사이드 이펙트를 일으킨 것으로 파악되어요
- #391 
-
-
> 작성 시 스크롤 이상 현상 수정

- apps/web/src/app/retrospect/analysis/RetrospectAnalysisPage.tsx
- apps/web/src/component/retrospect/analysis/PendingAnalysisingComp.tsx
> hotfix: #391 Add PendingAnalysisPeople

- apps/web/src/component/common/input/TextArea.tsx
- apps/web/src/style/global.css
> ### firefox textarea overflow 문제 수정
---
- 이슈 참고
-
- #349 
- https://stackoverflow.com/questions/41039127/css-height-effect-on-cross-browser
> 크로스브라우징 - Firefox textarea overflow 문제 수정

- apps/web/src/component/BottomSheet/BottomSheet.tsx
- apps/web/src/layout/GlobalLayout.tsx
> ### 공지사항 이메일 -> 채널톡으로 변경
---
- 이메일 -> 채널톡
- 텍스트 일부 강조 스타일 적용
-
- #420 
-
> 공지사항 이메일 -> 채널톡으로 변경

- apps/web/src/hooks/useToast.ts
---
- 체리픽해서 토스트 중복 생성 이슈만 머지해요~
- apps/web/src/hooks/useToast.ts
> fix: 회고 추천 플로우에서 에러 토스트 중복 생성 이슈 해결

- package.json
- pnpm-lock.yaml
> ### kr-corekit 유틸 라이브러리 패키지를 설치했어요
---
- kr-corekit 패키지 라이브러리 설치
- package.json
- closes: #512
> kr-corekit 패키지 설치
