- .github/workflows/build-test.yml
---
- 빌드 테스트하는 워크플로우의 문법 오류 수정
- `-main` -> `- main`
-
-
> fix/1/build workflow 문법 오류 수정

- .github/workflows/build-test.yml
- src/app/MainPage.tsx
> ### main 브랜치명 추가
---
- main 브랜치명 추가
- 포크해서 PR하는 경우 워크플로가 작동을 안하더라구요!
- 포크하고 PR하는 경우 브랜치명 앞에 organization/repo 가 붙는데 이 부분 때문인 것 같아요. 추가해줬습니다!
-
-
> chore: #1 포크의 경우 main브랜치 이름 추가

- src/component/common/Card/ListItemCard.tsx
- src/component/common/Radio.tsx
- src/component/common/RadioButton/Radio.tsx
- src/component/common/RadioButton/RadioButtonGroup.tsx
- src/store/context/RadioContext.ts
> ### 라디오 버튼 컴포넌트
---
- 커스텀 라디오버튼 컴포넌트 작성
- `ListItemCard`: 라디오버튼 형태가 라디오버튼 뿐만 아니라 아래와 같은 경우들에도 쓰일 것 같아 공통 컴포넌트로 빼두었습니다. 이 경우에도 카드라고 칭하는게 적합한지 모르겠는데 더 좋은 이름 있으면 추천해주세요..!
<br><br>
- `라디오 버튼`: 아래와 같이 작성하면 영상과 같이 작동합니다.
```tsx
const [selectedValue, setSelectedValue] = useState<string>();
return (
<RadioButtonGroup radioName={"프로젝트 주기"} selectedValue={selectedValue} onChange={setSelectedValue}>
<Radio value={"0"}>주 1회</Radio>
<Radio value={"1"}>월 1회</Radio>
<Radio value={"2"}>분기별</Radio>
<Radio value={"3"}>프로젝트 끝난 후</Radio>
</RadioButtonGroup>
);
``` 
https://github.com/depromeet/layer/assets/91667853/a46e007a-5e0a-4d79-882f-cb95c050752c
- #11 
- 커밋메시지에 이슈 번호를 #2로 잘못 적었네요.. 몇개 깜빡하고 누락도 됐어요 죄송합니다아
- 원래는 라디오 버튼에 국한되지 않고 props로 다중 선택이 가능하도록 지정하면 다중 선택도 가능하도록 개발하고 싶었는데, PR이 늦어질 것 같아 우선 라디오버튼이라도 …
> Feature/2/커스텀 라디오 버튼

- src/app/test/Staging.tsx
- src/component/common/CheckBox/CheckBox.tsx
- src/component/common/CheckBox/CheckBoxGroup.tsx
- src/component/common/RadioButton/Radio.tsx
- src/component/common/RadioButton/RadioButtonGroup.tsx
- src/hooks/useCheckBox.ts
- src/hooks/useRadioButton.ts
- src/layout/GlobalLayout.tsx
- src/store/context/CheckBoxContext.ts
- src/store/context/RadioContext.ts
> ### 중복선택 버튼 컴포넌트 (체크박스) 작성
---
- 중복 선택이 가능한 버튼그룹 (체크박스) 컴포넌트 개발
- 중복 선택이 불가한 버튼그룹 (라디오버튼) 컴포넌트 리팩토링 (체크박스와 사용방식 통일)
- `useRadioButton`, `useCheckBox` 훅 작성
- 각각 `selectedValue`, `setSelectedValues` (튜플의 세 번째 값) 값이 선택된 value 정보를 담고 있습니다.
- 라디오버튼은 input의 name 속성에 들어가는 `radioName` props를 추가로 전달해야 한다는 점 외에는 **라디오버튼, 체크박스 사용 방법이 같습니다**.
- #11 
- `Staging.tsx`에 **사용 예시**를 참고해주세요!
> 중복선택 버튼 컴포넌트 (체크박스) 작성

- src/app/test/Staging.tsx
- src/component/common/Input/Input.tsx
- src/component/common/Input/InputLabelContainer.tsx
- src/component/common/Input/Label.tsx
- src/component/common/Input/index.ts
- src/hooks/useInput.ts
- src/style/global.css
> ### Input, Label 컴포넌트
---
- Input, Input을 위한 Label, Input과 Label을 포함하는 컨테이너 컴포넌트 개발
- useInput 훅과 함께 사용
관련 변경 파일들입니다!
- src/component/common/Input/Input.tsx
- src/component/common/Input/Label.tsx
- src/component/common/Input/InputLabelContainer.tsx
- src/hooks/useInput.ts
<br>  
- 사용 예시 (Staging.tsx)
```tsx
<InputLabelContainer id={"retro"}>
<Label order={1}>회고 이름</Label>
<Input onChange={handleChangeName} value={layerName} />
</InputLabelContainer>
```  
- `InputLabelContainer`에 id를 전달하면 라벨과 인풋에 해당 id가 부여됩니다.
- `InputLabelContainer`에는 라벨과 인풋을 감싸는 부모 엘리먼트를 포함합니다. (간격 스타일 포함)
- `Label`의 `order` prop 은 라벨에 포함될 넘버링을 나타냅니다. 전달하지 않으면 넘버링 없이 텍스트 라벨만 출력됩니다. (아래 예시)
- #11 
-
> Input, Label 공통 컴포넌트 개발 (+ 컨테이너, 훅)

- src/component/common/header/Header.tsx
- src/component/common/header/index.ts
- src/component/common/typography/Typography.tsx
> ### 공통 헤더 컴포넌트 개발
---
- 공통 헤더 컴포넌트 개발
- src/component/common/header/Header.tsx
- src/component/common/typography/Typography.tsx
- src/component/common/typography/Typography.tsx
- #11 
- 사용 방법은 아래와 같습니다.
```jsx 
/** 
* title : 헤더 상단의 제목을 의미합니다. (required)
* contents : 헤더를 보조하는 내용을 의미합니다.
* - 제목 또는 내용을 줄바꿈하고 싶다면 `\n`를 넣으면 자동으로 줄바꿈으로 인식합니다.
* theme : 헤더 테마를 의미합니다. (primary/white)
*/
<Header title={`회고를\n작성해볼까요?`} content={"총 5개의 질문으로 구성되어있어요"} theme={"primary"}/>
```
> 공통 헤더 컴포넌트 개발

- src/app/test/Staging.tsx
- src/component/common/input/Input.tsx
- src/component/common/input/TextArea.tsx
- src/component/common/input/index.ts
- src/hooks/useCheckBox.ts
- src/hooks/useInput.ts
- src/hooks/useRadioButton.ts
- src/style/global.css
- src/style/variable.ts
> ### Input, TextArea 글자 수 카운트 추가
---
- TextArea 컴포넌트 추가
- Input과 동일하게 사용하시면 됩니다. (훅도 동일하게 `useInput` 사용)
- 글자 수 세는 기능 추가
- maxLength, count 전달
- src/component/common/input/Input.tsx
- src/component/common/input/TextArea.tsx
- src/hooks/useInput.ts
- #11
> Input, TextArea 글자 수 카운트 추가

- src/component/common/typography/Typography.tsx
> ### Typography children 타입 수정
---
- children 타입을 React.ReactNode로 수정했습니다.
- 띄어쓰기가 안되는 문제 해결
- 
- #11 
-
> Typography children 타입 수정

- src/app/retrospectCreate/RetrospectCreate.tsx
- src/component/home/NavigaionBar.tsx
- src/component/retrospectCreate/customTemplate/ConfirmDefaultTemplate.tsx
- src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
- src/component/retrospectCreate/customTemplate/EditQuestions.tsx
- src/component/retrospectCreate/customTemplate/questions.const.ts
- src/config/paths.ts
- src/layout/HomeLayout.tsx
- src/router/index.tsx
> ### 회고 생성 시 필수 질문 자동 삽입, 홈 라우터 수정
---
- 회고 생성 시 템플릿 질문 리스트에 필수 질문 삽입
- 홈 라우터 수정 (/home 제거, 루트로 지정)
- src/app/retrospectCreate/RetrospectCreate.tsx
- src/router/index.tsx
- src/component/home/NavigaionBar.tsx
- #35 
- 라우터에서 path를 지정하지 않으면 (index: true인 경우) `browserRouter`에서 path가 없다고 판단해서 빈 화면을 띄우더라구요!
- 그래서 임시로 path: '' 로 작성해두었습니다. (정상 작동)
> 회고 생성 시 필수 질문 자동 삽입, 홈 라우터 수정

- src/component/write/modal/TemporarySaveModal.tsx
> ### 모바일 사파리 환경 fit-content 속성 버그 대응
---
- 모바일 사파리 환경에서 modal의 fit-content 속성이 정상적으로 적용되지 않는 현상 대응
- src/component/write/modal/TemporarySaveModal.tsx
- #75 
- https://stackoverflow.com/questions/60052794/css-widthfit-content-not-working-on-iphones
> 모바일 사파리 환경 fit-content 속성 버그 대응

- src/component/common/Modal/FullModal.tsx
- src/component/retrospectCreate/steps/DueDate.tsx
> ### 회고 생성 날짜, 모달 버튼 배경 관련 버그 수정
---
- 날짜만 선택할 경우 input에 값이 안뜨는 버그 수정
- 질문 리스트 모달에서 [ButtonProvider가 읽기 위한 배경색 변수 추가](https://github.com/depromeet/layer/pull/74#discussion_r1705710169)
- 
- 
-
> 회고 생성 날짜, 모달 버튼 배경 관련 버그 수정

- src/component/write/phase/Write.tsx
> ### 사용자가 작성을 완료 후, 임시 저장 시 오류 방지를 위한 로직 설계
---
- 사용자가 작성을 완료 후, 임시 저장 시 오류 방지를 위한 로직 설계를 했어요.
- 기존에는 작성을 완료 한 사용자가 좌측 상단의 취소 버튼을 누르게 되면, 임시 저장 모달이 뜨게되는데 해당 버튼을 누르면 오류(400)가 발생했어요.
- 이 문제를 해결하기 위해 사용자가 만약 답한 데이터가 있을 경우, 임시 저장 API를 호출하는 것이 아닌 경고 문구만을 띄어주게 설계했어요
- src/component/write/phase/Write.tsx
- #73 
- 이미 사용자가 등록해놓은 데이터가 있는 경우
- 사용자가 임시 저장 또는 새로 글을 등록하는 경우
> 사용자가 작성을 완료 후, 임시 저장 시 오류 방지를 위한 로직 설계

- src/hooks/api/write/useGetAnswers.ts
> ### 회고 작성 시, 사용자 답변을 불러오는 API의 쿼리 키 누락 수정
---
- 회고 작성 시, 사용자 답변을 불러오는 도중 잘못된 캐싱 처리로 인한 문제를 수정합니다.
- src/hooks/api/write/useGetAnswers.ts
- closes: #82
-
> 회고 작성 시, 사용자 답변을 불러오는 API의 쿼리 키 누락 수정

- package.json
- pnpm-lock.yaml
> ### 프로젝트에 맞는 패키지 매니저를 사용하기 위한 `preinstall`을 설치해요
---
- `pnpm`을 사용하기 위한 `preinstall`을 `package.json`에 명시했어요.
- package.json
- #101 
- 관련 내용이 궁금하다면? : https://pnpm.io/ko/8.x/only-allow-pnpm
> 다른 패키지 매니저를 사용하지 않도록 설치 스크립트 추가

- package.json
- pnpm-lock.yaml
- src/component/common/header/Explanation.tsx
- src/component/common/header/Title.tsx
- src/component/write/modal/TemporarySaveModal.tsx
- src/component/write/phase/Prepare.tsx
- src/component/write/phase/Write.tsx
> ### 회고 작성 시 임시 저장 플로우를 변경
---
- 회고 작성 시 임시 저장 플로우를 변경했어요
- 기존 작성한 사용자에게 제공되지 않던 임시 저장 방어 코드를 제거하고, 수정된 API에 맞게 재구성했어요
- 로딩을 마치고 사용자가 회고를 완료한 경우에는 회고 데이터를 기본적으로 셋하고, 회고 데이터가 있는 경우 모달을 띄어 사용자에게 해당 데이터를 이어서 작성할 것인지 물어보는 플로우를 추가했어요
- src/component/write/phase/Write.tsx
- src/component/write/modal/TemporarySaveModal.tsx
- #91 
https://github.com/user-attachments/assets/523688b5-4ebf-4abd-afa8-6acc72f78ae3
> 회고 작성 시 임시 저장 플로우 변경

- src/app/space/SpaceViewPage.tsx
- src/component/common/appBar/AppBar.tsx
- src/layout/DefaultLayout.tsx
- src/layout/DualToneLayout.tsx
- src/style/global.css
> ### 앱바 높이 변수 처리에 따른 수정 + DualToneLayout 버그 수정
---
- 앱바 높이 변수 처리에 따른 수정
- 앱바 높이만큼의 self closing div 삭제, main 영역에 padding-top 처리 + height 100dvh
- DualToneLayout 버그 수정 (#109 해당 이슈는 자식인 AppBar가 fixed인 반면 이를 감싸는 부모가 sticky 속성이라 제대로 동작이 안됐던 것 같습니다. → sticky를 fixed로 수정했습니다)
-
- #109 
-
> 앱바 높이 변수 처리에 따른 수정 + DualToneLayout 버그 수정

- src/app/retrospectCreate/RetrospectCreate.tsx
- src/component/common/input/TextArea.tsx
- src/component/retrospectCreate/customTemplate/AddQuestionsBottomSheet.tsx
- src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
- src/component/retrospectCreate/customTemplate/EditQuestions.tsx
- src/component/retrospectCreate/steps/CustomTemplate.tsx
- src/component/retrospectCreate/steps/DueDate.tsx
- src/component/retrospectCreate/steps/Start.tsx
- src/hooks/api/template/usePostRecentTemplateId.ts
- src/store/retrospect/retrospectCreate.ts
- src/store/templateAtom.ts
> ### 회고 생성 플로우 수정, 페이지 이탈 시 템플릿 임시저장
---
- 질문 수정 앞뒤로 이동하는 플로우 수정사항 반영
- 페이지 나갈 때 임시저장 API 연결
- 질문 개수 초과했을 때 에러 토스트
- src/app/retrospectCreate/RetrospectCreate.tsx
- src/component/retrospectCreate/steps/Start.tsx
- src/component/retrospectCreate/customTemplate/EditQuestions.tsx
- src/component/retrospectCreate/customTemplate/AddQuestionsBottomSheet.tsx
- src/hooks/api/template/usePostRecentTemplateId.ts
- #105 
- 현재 추천 질문 체크할 때 체크는 개수 제한 없이 가능하고, `추가하기` 버튼을 최종적으로 눌러야 개수 초과 여부를 판단해 토스트를 띄웁니다. 사실 사용자가 체크할 때마다 개수 초과 여부를 판단해서 초과할 때는 바로 에러 토스트를 띄우는 게 더 좋은 사용자 경험을 제공할 것 같다는 생각을 했어요. 근데 만들어놨던 체크박스 컴포넌트가 리팩토링이 꽤 들어가게 될 것 같아서 이건 좀 더 고려해보고 별도 PR로 올리도록 할게요!
> 회고 생성 플로우 수정, 페이지 이탈 시 템플릿 임시저장

- src/component/space/join/JoinSpace.tsx
- src/config/storage-keys.ts
- src/hooks/api/login/usePostSignIn.ts
- src/layout/RequireLoginLayout.tsx
- src/router/index.tsx
> ### auth가 필요한 페이지 로그인 후 리다이렉트
---
- auth: true로 설정된 페이지는 로그인 페이지로 리다이렉트 후, 로그인 성공 시 다시 접속 시도했던 페이지로 돌아오게 처리했습니다. (Cookie)
-
- #126 
-
> auth가 필요한 페이지 로그인 후 리다이렉트

- src/component/write/phase/Write.tsx
- src/hooks/api/write/useGetAnswers.ts
- src/hooks/api/write/useGetTemporaryQuestions.ts
> ### 회고 작성 시 이전 데이터를 불러오는 현상 수정
---
- 회고 작성 시 이전 데이터를 불러오는 현상 수정을 했어요
- 윈도우 창을 벗어났을 때 리패치를 하는 요소들을 제거했어요
- src/component/write/phase/Write.tsx
- src/hooks/api/write/useGetAnswers.ts
- src/hooks/api/write/useGetTemporaryQuestions.ts
- #133 
-
> 회고 작성 시 이전 데이터를 불러오는 현상 수정

- src/app/retrospectCreate/RetrospectCreate.tsx
- src/app/retrospectCreate/RetrospectCreateComplete.tsx
- src/app/space/SpaceViewPage.tsx
- src/component/space/CreateRetrospectiveSheet.tsx
- src/component/space/view/SpaceAppBarRightComp.tsx
- src/hooks/useMultiStepForm.ts
> ### 대표템플릿 저장 및 불러오기 로직 반영
---
- 템플릿 추천받아 회고 생성 이탈하는 경우에**만** `템플릿 저장` 모달 띄우기
- 대표 템플릿이 있는 경우 회고 생성 버튼 클릭 시 `대표 템플릿 사용 여부 확인` 모달 띄우기
- src/app/retrospectCreate/RetrospectCreate.tsx
- src/app/space/SpaceViewPage.tsx
- src/component/space/CreateRetrospectiveSheet.tsx
- src/component/space/view/SpaceAppBarRightComp.tsx
- 회고 생성 버튼을 눌렀을 때 바텀시트가 바로 뜨지 않고 모달을 먼저 띄우기 때문에 변수명을 조금 수정했습니다! @sean2337 
- #105
-
> 대표템플릿 저장 및 불러오기 로직 반영

- pnpm-lock.yaml
- src/app/actionItem/ActionItemEditPage.tsx
- src/app/actionItem/ActionItemMorePage.tsx
- src/app/space/SpaceViewPage.tsx
- src/app/test/Staging.tsx
- src/component/BottomSheet/BottomSheet.tsx
- src/component/BottomSheet/component/BottomSheetHeader.tsx
- src/component/common/SelectBox/SelectBox.tsx
- src/component/common/SelectBox/index.ts
- src/component/common/dateTimePicker/DateTimePicker.tsx
- src/component/common/input/DateTimeInput.tsx
- src/component/retrospect/template/list/CustomTemplateListItem.tsx
- src/component/retrospectCreate/customTemplate/EditQuestions.tsx
- src/component/space/view/ActionItemListView.tsx
- src/hooks/useBottomSheet.ts
- src/router/index.tsx
> ### 한 화면에서 바텀시트가 여러 개 정상 동작되도록 리팩토링
---
- 한 화면에서 바텀시트가 여러 개 정상 동작되도록 리팩토링을 진행했어요
- 커밋 내용 참조를 부탁드려요
- 여러분들이 작업하신 바텀시트의 경우 변경된 사항으로 리팩토링 마이그레이션을 같이 진행했어요
그러니 테스트만 부탁드려요 (제가 선 테스트를 진행하긴 했는데 혹시 모르니) 🙇🏻‍♂️
- #140 
- 기존에는 이렇게 시도를 했었어요
```jsx
openBottomSheet({
title: "테스트 바텀시트",
contents: <span> 테스트 바텀시트 </span>",
handler: false,
})
```
- 처음에는 바텀시트를 글로벌로 선언하고, 훅으로만 컨트롤을 하고 싶었는데 컴포넌트를 훅 형태로 넘기면 정적인 노드들의 경우 정상적으로 렌더링이 되지만 상태를 관리하는 동적 컴포넌트들의 경우 초기 렌더링 이후에 상태가 리렌더링 되지 않은 문제가 있더라구요,, 그래서 사용하는 화면에서만 바텀시트를 사용하도록 하였습니다, 기존 구조에서 혼동을 줄이기 위해 `id` 프로퍼티만 추가되었다고 쉽게 생각을 해주시면 될 것 같아요!
- 결국 아래와 같이 사용하기로 했습니다.. 🥹
```jsx
const { openBottomSheet } = useBottomSheet();
/** 바텀 시트는 아래와 같이 사용을 할 수 있어요, 사용자가 지정한 id 값을 통해 독립적인 바텀시트를 사용할 수 있어요 */ 
<Button onClick={() => openBottomSheet({ id: "hello1" })}> 그냥 그저 그런 버튼 …
```
> 한 화면에서 바텀시트가 여러 개 정상 동작되도록 리팩토링

- src/app/space/SpaceViewPage.tsx
- src/component/home/TagBox.tsx
- src/component/space/view/ActionItemListView.tsx
- src/component/space/view/SpaceAppBarRightComp.tsx
- src/component/space/view/SpaceCountView.tsx
- src/hooks/api/actionItem/useApiPostActionItem.ts
- src/layout/DualToneLayout.tsx
- src/types/spaceType/index.ts
- src/utils/space/categoryTagChange.ts
- src/utils/space/categoryTagKoreanChange.ts
> ### 스페이스 뷰 페이지 1차 변경 및 리팩토링
---
- 스페이스 뷰 페이지 1차 변경 및 리팩토링를 완료했어요!
- 스페이스 뷰 페이지와 관련 컴포넌트, 함수를 수정했어요!
- 태그 별 한국말 변경 함수는 제가 만든 것을 사용하면 될 것 같아요!! => `src/utils/space/categoryTagChange.ts`
- #118 
- 아직 해결해야되는 부분
1. ActionItem 생성이 왜 회고 ID를 받는지? SpaceId를 받아서 진행하는게 맞지 않나? => 논의 후 적용 예정
2. 팀 떠나기 API 오류 => 이거는 백엔드 문제인것 같아서 코드는 완료해둠 => API 수정되면 확인 필요.
3. 회고가 날짜가 지나도 상태가 그대로 유지되던데 백엔드와 이야기 필요 => 자동으로 업데이트가 안되는 것 같음. 
4. 액션 아이템 생성 TextArea width 해결
> 스페이스 뷰 페이지 1차 변경 및 리팩토링

- src/app/retrospect/template/list/TemplateListPage.tsx
- src/component/retrospect/template/list/CustomTemplateList.tsx
- src/component/retrospect/template/list/CustomTemplateListItem.tsx
- src/component/retrospect/template/list/DefaultTemplateListItem.tsx
- src/component/retrospect/template/list/index.ts
> ### 회고 생성 템플릿 리스트의 경우 옵션 버튼 제거
---
- 회고 생성 템플릿 리스트의 경우 옵션 버튼 제거
- spaceId를 포함해서 회고 생성에 해당하는 리스트인지에 대한 상태를 `TemplateListPage`에서 Context로 provide
- 
- #151
-
> 회고 생성 템플릿 리스트의 경우 옵션 버튼 제거

- src/component/common/tip/Tooltip.tsx
- src/component/retrospect/template/recommend/RecommendDone.tsx
- src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
> ### 툴팁 꼬리 위치 고정 값으로 수정
---
- 기존에는 툴팁 꼬리가 툴팁 기준이되는 컴포넌트의 중앙에 위치하게 하려는 의도로 기준 컴포넌트의 width를 가지고 위치를 계산했었는데, 툴팁꼬리가 툴팁 박스를 기준으로 움직이고, 툴팁 박스도 메시지에 따라 길이가 달라져서 어려울 것 같습니다.
- 툴팁 박스의 가장자리를 기준으로 2rem정도 안쪽으로 움직이도록 수정했습니다.
- x, y축 방향으로 이동시킬 거리를 튜플 형태에서 각각 number로 따로 받도록 수정했습니다.
- #88
-
-
> 툴팁 꼬리 위치 고정 값으로 수정

- package.json
- pnpm-lock.yaml
- src/app/actionItem/ActionItemEditPage.tsx
- src/component/actionItem/ActionItemBox.tsx
- src/component/actionItem/ActionItemModifyBox.tsx
> ### 액션 아이템 리스트 추가 패칭 작업 및 셔플 로직 추가
---
- 액션 아이템 리스트 추가 패칭 작업 및 셔플 로직 추가
- 커밋 내용 참조
- #35 
-
- `react-beautiful-dnd`를 이용한 리스트 셔플 기능을 사용하게 되면 개발 환경에서는 `StrictMode`를 제거해야 테스트를 할 수 있어요, 이에 따라 해당 코드를 지우거나 배포 환경에서 테스트가 가능한데 `@hello-pangea/dnd` 라이브러리로 대체를 하게 되면 개발 환경에서도 테스트가 가능할 뿐만 아니라 컴포넌트 사용 방법도 동일해요!
https://github.com/user-attachments/assets/59266d02-7514-461a-8b4e-2f5e4b113ad2
> 액션 아이템 리스트 추가 패칭 작업 및 셔플 로직 추가

- src/app/space/CreateNextPage.tsx
- src/app/space/SpaceViewPage.tsx
- src/component/retrospect/template/recommend/RecommendDone.tsx
- src/router/index.tsx
> ### 스페이스 생성 완료 후 추천 페이지로 이동
---
- 임시로 회고 생성으로 넘어가게 작성했던 플로우를 제거했습니다.
- 템플릿 추천 완료 후, 회고 생성으로 바로 넘어갈 때 `templateId`, `saveTemplateId` state를 추가로 전달합니다.
- '전에 진행했던 템플릿이 있어요. 계속 진행하시겠어요?' 모달에서 '진행하기'를 클릭한 경우는 새로 템플릿 ID를 대표 템플릿으로 지정하지 않도록 수정했습니다. (불필요하게 API 호출하지 않도록) 
-
-
-
> 스페이스 생성 완료 후 추천 페이지로 이동

- src/app/template/TemplatePage.tsx
- src/component/retrospect/template/recommend/RecommendDone.tsx
> ### 템플릿 오류를 수정했어요
---
- 대표 템플릿에서 템플릿 상세보기를 접속한 경우에는 [선택하기] 버튼이 없어야 함 (해당 파트에서는 리스트 정보 확인만 가능)
- 무제 템플릿에 ‘이런 목적으로 사용하기 좋아요’ 워딩이 2번 반복되어있음
- src/app/template/TemplatePage.tsx
- src/component/retrospect/template/recommend/RecommendDone.tsx
- #151 
-
> [QA] 템플릿 오류 수정

- src/component/space/view/ActionItemListView.tsx
> ### 완료된 회고가 없는 경우 액션 아이템의 더보기 버튼이 노출되는 현상
---
- 완료된 회고가 없는 경우 액션 아이템의 더보기 버튼이 노출되는 현상을 수행했어요
- src/component/space/view/ActionItemListView.tsx
- #186 
-
> [QA] 완료된 회고가 없는 경우 액션 아이템의 더보기 버튼이 노출되는 현상

- src/hooks/useDateTimePicker.ts
> ### DateTimePicker 반환값 timezone offset 제거
---
- 일관성을 위해 ISO string의 timezone offset 부분을 제거했습니다.
- 이슈 참고
- 
- #191
-
> DateTimePicker 반환값 timezone offset 제거

- src/app/retrospect/template/list/TemplateListPage.tsx
- src/app/template/TemplatePage.tsx
- src/component/retrospect/template/list/CustomTemplateList.tsx
- src/component/retrospect/template/list/DefaultTemplateListItem.tsx
- src/component/retrospect/template/recommend/RecommendDone.tsx
- src/component/space/view/SpaceCountView.tsx
> ### 템플릿 버튼 ReadOnly 로직 수정
---
- 템플릿 버튼 ReadOnly 로직 수정을 진행했어요
- 커밋 내용을 참고해주세요
- #151 
-
- @donghunee 요청대로 회고 생성 시에 템플릿 페이지를 조회하는 플로우에 대한 버튼 노출 로직을 설계했고, 
스페이스에서 확인할 수 있는 템플릿 페이지 조회 로직에는 버튼이 노출되지 않도록 설계했어요.
- 해당 PR을 올린 배경은 현재 템플릿 상세 조회 페이지로 이동하는 과정을 여러 곳에서 요청을 하고 있어요
1. 스페이스 뷰에서 `대표 템플릿` 란을 통해 단순 템플릿 내용을 조회하는 순간
2. 회고 생성 중 템플릿 조회 페이지로 이동하여 템플릿을 선택하는 순간
-  로직을 일부 수정하면서 느꼈는데 지금 템플릿 상세 조회 페이지로 이동하는 과정에서 상태 관리가 점점 복잡해진다고 생각했어요, 지금은 일일히 명시를 하여 구현을 진행했는데 더 좋은 방법이 있는지, 혹은 리팩토링을 어떤 방식으로 진행할 수 있는지 같이 이야기를 나눠보면 좋을 것 같아요!
> [QA] 템플릿 버튼 ReadOnly 로직 수정

- src/app/retrospect/template/list/TemplateListPage.tsx
- src/app/template/TemplatePage.tsx
- src/component/retrospect/template/list/CustomTemplateListItem.tsx
- src/component/retrospect/template/list/DefaultTemplateListItem.tsx
- src/component/space/CreateRetrospectiveSheet.tsx
> ### 템플릿 리스트 - 템플릿 상세 - 회고 생성 관련 라우팅
---
- 템플릿 리스트 아이템 → 템플릿 상세 라우팅 클릭 영역 수정 (버튼에서 카드 전체로)
- 템플릿 상세 페이지 → 선택하기 → 회고 생성 페이지 라우팅 연결
-
- #151 
-
> 템플릿 리스트 - 템플릿 상세 - 회고 생성 관련 라우팅

- src/app/retrospect/template/list/TemplateListPage.tsx
- src/component/common/dropdownMenu/DropdownMenu.tsx
- src/component/common/empty/EmptyList.tsx
- src/component/common/empty/index.ts
- src/component/retrospect/template/list/CustomTemplateList.tsx
- src/component/retrospect/template/list/CustomTemplateListItem.tsx
> ### 템플릿 리스트 빈 화면 추가
---
- 템플릿 리스트 빈 화면 추가
- 템플릿 이름 수정 후 바텀시트 닫기
- 드롭다운 버튼 클릭 이벤트 버블링 차단 (템플릿 상세로 이동 차단)
-
- #151 
-
> 템플릿 리스트 빈 화면 추가

- src/component/retrospectCreate/customTemplate/EditQuestions.tsx
- src/types/retrospectCreate/index.ts
> ### 기본 템플릿 수정여부 필드 반대로 된 문제 수정
---
- #239 해당 PR에서 boolean만 반대로입니다!
-
- #235 
-
> 기본 템플릿 수정여부 필드 반대로 된 문제 수정

- src/hooks/api/retrospect/useApiDeleteRetrospect.ts
- src/hooks/api/retrospect/useApiOptionsGetRetrospects.ts
- src/hooks/api/template/useDeleteCustomTemplate.ts
- src/hooks/api/template/usePatchTemplateTitle.ts
> ### 회고, 템플릿 수정 및 삭제 낙관적 업데이트
---
- 템플릿 이름 수정 낙관적 업데이트
- 템플릿 삭제 낙관적 업데이트
- 회고 삭제 낙관적 업데이트
-
- #193 
- 현재 쿼리 키를 상수처리하지 않고 그대로 사용하고 있어요. 외부에서 제어하고 있는 쿼리 키는 `FIXME` 주석을 달아두긴 했는데, 추후 상수로 리팩토링 해야 쿼리 키 수정으로 인해 생기는 버그를 방지할 수 있을 것 같아요!
> 회고, 템플릿 수정 및 삭제 낙관적 업데이트

- src/component/space/join/JoinSpace.tsx
- src/hooks/api/login/usePostAppleToken.ts
- src/hooks/api/login/usePostSignIn.ts
- src/hooks/api/login/usePostSignUp.ts
> ### 초대 페이지에서 로그인 성공한 케이스 처리
---
- 초대 페이지에서 로그인 성공한 케이스 처리
- 애플 로그인해서 초대 수락된 경우 멘트 수정 ('첫 스페이스~' → '스페이스에 초대되었어요')
- 처리 후 space id 쿠키 삭제
-
- #269 
-
> hotfix: #269 초대 페이지에서 로그인 성공한 케이스 처리

- src/hooks/api/write/useWriteQuestions.ts
> ### 회고 작성 시 range 데이터 0~100 단위로 수정
---
- 분석 응답 데이터를 0부터 100까지 퍼센티지로 반환하고 있는데, 회고 작성 시 0부터 4까지 인덱스값으로 POST해서 분석 데이터가 부정확하게 나오는 문제
→ 작성 시 0부터 100까지 20 단위로 POST
@klmhyeonwoo 
-
-
-
> hotfix: #269 회고 작성 range 0~100 단위로 수정

- src/app/retrospect/analysis/RetrospectAnalysisPage.tsx
- src/component/retrospect/analysis/InsightsBoxSection.tsx
- src/component/space/view/RetrospectBox.tsx
- src/component/space/view/RetrospectButton.tsx
> ### hotfix: 분석 페이지 제목, 이름 수정
---
- 분석 페이지 제목 반영
- 개인 분석의 경우 '우리팀' -> 유저 이름으로 수정
-
-
-
> hotfix: 분석 페이지 제목, 이름 수정

- src/component/write/phase/Write.tsx
- src/component/write/template/complete/Achievement.tsx
- src/component/write/template/write/write.const.ts
- src/hooks/api/retrospect/analysis/useGetAnalysisAnswer.ts
- src/hooks/api/write/useGetAnswers.ts
- src/hooks/api/write/useGetTemporaryQuestions.ts
- src/hooks/api/write/useWriteQuestions.ts
> ### 사용자가 설정한 목표 달성 범위가 정상 출력되지 않습니다.
---
- 사용자가 설정한 목표 달성 범위가 정상 출력되지 않아 관련 로직을 추가 및 수정 진행하였어요
- 커밋 내용을 참고해주세요
- #307 
- 컴포넌트 내부적으로는 목표 달성 범위에 대한 Range 관리를 index로 진행하고, 서버 측에서 데이터를 전송하거나 받아올 때의 경우에는 실제 퍼센테이지로 관리가 되어야하기 때문에 스케일 처리를 진행하도록 로직을 추가하였습니다!
- 서버 전송 시 : 퍼센테이지로 변환
- 서버에서 응답 값으로 받았을 때 : 퍼센테이지에서 인덱스로 변환
기존에는 index 형태로 넘기 받으면서 범위 처리를 진행하고 있었으나, 분석 기능 추가로 인해 퍼센테이지로 전송을 해야 서버에서 해당 값을 받아 분석 데이터에 사용하기 때문에
> 사용자가 설정한 목표 달성 범위가 정상 출력되지 않습니다.

- index.html
- src/component/login/SocialLoginArea.tsx
- src/utils/etc.ts
> ### 카카오 로그인 모바일 환경일 시 앱을 통한 로그인 구현
---
- 카카오 로그인 모바일 환경일 시 앱을 통해 로그인하였어요.
- 다만 문제가 사파리의 경우, 앱을 통한 로그인 변수인 `throughTalk`을 인지하지 못해, 사파리의 경우는 카카오 페이지 이동이 불가피하다고 해요! 
- 현재 구현 상태
1. 모바일 (사파리 제외) : 앱을 통해 로그인 ( 앱이 설치되어있을시)
2. 그 외: 이전 방법 ( 사파리 + 앱이 설치 안된 모바일 등)
=> 앱이 설치되어있는 모바일 환경이면 앱을 통한 로그인을 시도해요!
- 커밋 참고
- #319 
- 현재 현우형이 알려준걸로 테스트 했는데 API 호출까진 가는거 확인, 근데 Redirection URL이 달라서 로그인 성공인지는 확인 못함. 
=> 스테이징에서 테스트 해볼 예정
> 카카오 로그인 모바일 환경일 시 앱을 통한 로그인 구현

- src/hooks/api/login/usePostKakaoToken.ts
> ### SDK를 적용한 카카오톡 앱 내 로그인 적용
---
- SDK를 적용해서 카카오 브라우저로 이동하는게 아닌 앱으로 로그인할 수 있도록 변경했어요. 
- 다음과 같은 요구사항으로 시작되었어요.
=> 카카오톡 앱에서 로그인 시에 뒤로가기가 없어서 로그인하고 안하고 싶다면 앱을 꺼야돼요! + 그리고 앱으로 로그인하는 것도 있던데, 아이디 치는게 번거로워요.
- 구현방식
---
- 뒤로가기 삽입
뒤로 가기 삽입의 경우, 카카오톡 자체 웹 사이트이므로 삽입이 불가능하고, 넣고 싶다면 iframe태그를 써서 하는 방식 밖에 없었어요. 하지만 이는 보완에 좋지 못하다고 해요. 이에 따라 뒤로가기 이전에 그냥 앱 자체로 로그인할 수 있도록 하여 이 문제를 자연스럽게 해결하고자 했어요.
---
- 앱 내 로그인 방식
1. 카카오톡이 깔려있는 모바일 => SDK를 활용하여 앱 내 로그인이 될 수 있게 했어요.
2. 카카오톡이 깔려있지 않은 모바일 + 데스크톱 웹 => 기존과 동일하게 아이디, 비밀번호를 입력하게 하였어요. 
3. 사파리 웹 : 사파리의 경우 카카오톡이 깔려있어도 앱 내 로그인이 불가능했어요. 이는 SDK를 적용할 수 있는 변수인 `throughTalk` 를 호환하지 못해 에러가 발생했어요. 이에 따라서 사파리와 같이 `throughTalk`를 호환하지 못해 에러가 발생하는 경우 기존 방식을 적용했어요.
정리: 앱으로 로그인할 수 있을땐 앱 내 로그인을 하고 그렇지 않은 경우는 기존 방식 유지 
---
- 커멋 사항 참조
- #319 
- Safari에서 호환하지 못하는 원인
=> 원인 분석을 …
> SDK를 적용한 카카오톡 앱 내 로그인 적용

- apps/mobile/app.config.ts
- apps/mobile/app/_layout.tsx
- apps/mobile/babel.config.js
- apps/mobile/env.d.ts
- apps/mobile/ios/Podfile.lock
- apps/mobile/layout/webview-layout/index.tsx
- apps/mobile/package.json
- pnpm-lock.yaml
>환경변수 의존성 제거
---
- Expo 51 버전에서 `react-native-dotenv`를 사용할 경우, `expo-router`를 사용할 수 없는 이슈가 있어, 제거했습니다
-
-
-
> 환경변수 의존성 제거

- apps/web/src/hooks/useEditQuestions.ts
> ### 삭제한 아이템이 없을 때 완료 버튼 누르면 토스트 나오지 않도록
---
- 삭제한 아이템이 없을 때는 삭제 완료 토스트를 띄우지 않도록 early 리턴해주었습니다.
-
-
-
> 삭제한 아이템이 없을 때 완료 버튼 누르면 토스트 나오지 않도록

- apps/web/src/component/home/SummaryInsightBox.tsx
> ### 분석 페이지 포인트가 없을시 조건 추가
---
- 분석 페이지 포인트가 없을시 기존 컴포넌트를 보여줬는데 안보이게끔 조건문을 추가했어요.
-  apps/web/src/component/home/SummaryInsightBox.tsx
- #391
-
> 분석 페이지 포인트가 없을시 조건 추가

- apps/web/src/app/retrospectCreate/RetrospectCreateComplete.tsx
- apps/web/src/app/write/RetrospectWritePage.tsx
- apps/web/src/component/space/view/RetrospectBox.tsx
- apps/web/src/component/write/phase/Write.tsx
- apps/web/src/component/write/template/complete/ResultContainer.tsx
- apps/web/src/hooks/api/retrospect/create/usePostRetrospectCreate.ts
> fix: #391 Fixed Plain Text Container Style

- apps/web/src/layout/GlobalLayout.tsx
- apps/web/src/lib/channel-talk/service.ts
- apps/web/src/router/index.tsx
> ### 내정보 페이지 채널톡 연동
---
- 내정보 화면 `/myinfo`에 채널톡 버튼 추가
-
- #416 
- 채널톡은 SPA 환경에서 경로가 변경되는 걸 인지하지 못해서, GlobalLayout에 location 변경될 때마다 경로 판단해서 내정보 페이지 (마이페이지)일 경우만 버튼 띄우게 해놨습니다. 
- 혹시 더 좋은 방법이 있다면 알려주세요오
> 내정보 페이지 채널톡 연동

- apps/web/src/helper/preventExternalBrowser.tsx
> ### 카카오 인앱 브라우저에서도 서비스 화면 그대로 띄우도록 재수정
---
- 기존에 서비스 브라우저를 이용해주세요 라고 서비스 화면을 안 띄우도록했는데, 다시 띄우도록 변경하였습니다.
- 커밋 내용 참조
- #409 
-
> fix: #409 카카오 인앱 브라우저에서도 서비스 화면 그대로 띄우도록 재수정

- apps/web/src/app/actionItem/ActionItemEditPage.tsx
- apps/web/src/component/actionItem/ActionItemBox.tsx
---
- 특정 회고의 실행목표를 편집하려고 할 때, 해당 회고의 실행목표만 나오는 것이 아닌 스페이스의 모든 실행목표가 보이고 편집이 가능했습니다.
- 모든 retrospectInfo를 전달하기보다 특정 회고의 id로 걸러진 retrospectInfo만 ActionItemEditPage 페이지로 넘기도록 변경했습니다.
- #443 
https://github.com/user-attachments/assets/3e12bf8b-9939-4363-86d3-f18c69c5419b
close #443
> fix: 실행목표 편집 에러 수정

- apps/web/src/app/actionItem/ActionItemEditPage.tsx
- apps/web/src/component/actionItem/ActionItemBox.tsx
---
- 특정 회고 실행 목표 편집 버그 수정 
-  모든 retrospectInfo를 전달하기보다 특정 회고의 id로 걸러진 retrospectInfo만 ActionItemEditPage 페이지로 넘기도록 변경
- #449
> Merge to main

- apps/web/src/router/index.tsx
- packages/shared/constants/paths/index.ts
> ### 데스크탑 라우트로 접근했을 때 모바일 라우트로 접근되도록 오류 수정
---
- 데스크탑 라우트로 접근했을 때 모바일 라우트로 접근되도록 오류 수정하는 작업을 진행했어요
- apps/web/src/router/index.tsx
- packages/shared/constants/paths/index.ts
- #480 
-
> fix: #480 데스크탑 라우트로 접근했을 때 모바일 라우트로 접근되도록 오류 수정

- apps/web/.eslintrc.cjs
- apps/web/src/component/common/StatusChips/index.tsx
- apps/web/src/component/home/SpaceOverview.tsx
- apps/web/src/types/spaceType/index.ts
- apps/web/tsconfig.json
> ### 디자인 요구사항 반영 작업
---
- 메인 리스트 레이아웃(칩, 텍스트) 개선하는 작업을 진행했어요
- apps/web/src/component/common/StatusChips/index.tsx
- 상태를 나타내는 스타일 칩 컴포넌트 추가 
- apps/web/src/component/home/SpaceOverview.tsx
- 회고 리스트 카드 뷰 레이아웃 수정
- apps/web/src/types/spaceType/index.ts
- 회고 리스트 카드 뷰 레이아웃 수정을 위한 일부 타입 추가
- close: #475
- 기존에 빨간 줄 뜨던 현상은.. `eslint` 파일의 `project` 프로퍼티가 잘못된 설정을 가지고 있어 빨간 줄이 뜨는 현상이 발생했더라구요..
- 이 설정을 하게 되면 아래와 같은 특징을 가지게 된다고 해요, 우리 프로젝트에서 IDE에서도 기본적으로 타입을 검사해주지만 아래의 것들은 `esline`의 `project` 설정이 있어야만 가능하다고 합니다!
• ESLint가 타입 정보를 이해하고 사용할 수 있습니다.
• no-floating-promises, no-unsafe-assignment, no-unnecessary-type-assertion 등 타입 기반 룰이 정확하게 작동합니다.
• import 경로 alias (@/)도 tsconfig.json의 paths, baseUrl을 바탕으로 올바르게 분석됩니다.
> 디자인 요구사항 반영 > 메인 리스트 레이아웃(칩, 텍스트) 개선

- apps/web/src/app/mobile/home/RetrospectViewPage.tsx
- apps/web/src/component/common/LocalNavigationBar/Navigation/Navigation.tsx
- apps/web/src/component/common/LocalNavigationBar/Navigation/space/SpaceItem.tsx
- apps/web/src/component/common/LocalNavigationBar/Navigation/space/SpaceTabs.tsx
- apps/web/src/component/common/LocalNavigationBar/Navigation/space/SpacesList.tsx
- apps/web/src/component/common/LocalNavigationBar/constants.ts
- apps/web/src/hooks/api/space/useApiGetSpaceList.ts
- apps/web/src/router/index.tsx
- apps/web/src/store/space/spaceAtom.ts
> ### LocalNavigationBar에서 선택한 스페이스 상태 관리
---
- 내 스페이스 목록 조회
- 무한스크롤 적용
- 선택한 스페이스에 대한 전역 상태 갱신 로직 추가 
- `apps/web/src/app/mobile/home/RetrospectViewPage.tsx`에서 사용되는 현재 선택된 카테고리를 나타내는 변수명 변경 
(`selectedView` -> `currentCategory`)
- #490 
- loading lottie는 기존의 존재하는 것을 사용했는데, 이걸 사용해도 될지는 얘기가 필요해보입니다..!
https://github.com/user-attachments/assets/ea5f451f-22e8-443a-8142-604b765eabd2
close #490
> feat: LNB에서 선택한 스페이스 상태 관리

- apps/web/src/app/desktop/home/HomePage.tsx
- apps/web/src/app/mobile/home/HomePage.tsx
- apps/web/src/app/mobile/space/SpaceViewPage.tsx
- apps/web/src/component/common/LocalNavigationBar/Navigation/space/SpacesList.tsx
- apps/web/src/component/common/LocalNavigationBar/index.tsx
- apps/web/src/component/home/HomePageHeader/index.tsx
- apps/web/src/component/home/InProgressRetrospectCard/index.tsx
- apps/web/src/component/home/InProgressRetrospectsWrapper/index.tsx
- apps/web/src/component/home/QuickActionButton/index.tsx
- apps/web/src/hooks/api/space/useApiGetSpaceList.ts
- apps/web/src/hooks/useNavigationState.ts
- apps/web/src/layout/DesktopHomeLayout.tsx
- apps/web/src/router/index.tsx
- apps/web/src/style/designTokens.ts
> ### 내 회고 리포트 작성중인 회고 UI 작업
---
- 홈 화면에 '내 회고 리포트'의 작성중인 회고 UI를 구현했습니다.
- '내 회고 리포트'의 `QuickActionButton` 컴포넌트를 추가했습니다.
- 작성중인 회고의 카드 컴포넌트(`InProgressRetrospectCard`)를 새롭게 추가했습니다.
- 스페이스 목록을 불러오는 커스텀훅을 개선하여, tanstack query의 옵션들을 자유롭게 설정할 수 있도록 개선했습니다.
- #488 
++ 코드리뷰 양 조절을 위해서 여기서 끊고 갈게요..!
close #488
> feat: 홈 화면 - 내 회고 리포트 작성중인 회고 UI 작업

- apps/web/src/app/desktop/component/analysis/AnalysisOverview/AnalysisOverviewHeader.tsx
- apps/web/src/app/desktop/component/analysis/AnalysisOverview/InProgressRetrospectsWrapper.tsx
- apps/web/src/app/desktop/component/analysis/AnalysisOverview/RetrospectSection.tsx
- apps/web/src/app/desktop/component/analysis/AnalysisOverview/index.tsx
- apps/web/src/app/desktop/component/home/InProgressRetrospectCard/index.tsx
- apps/web/src/app/desktop/component/home/InProgressRetrospectsWrapper/index.tsx
- apps/web/src/app/desktop/retrospect/AnalysisPage.tsx
- apps/web/src/component/common/LocalNavigationBar/Navigation/HomeButton.tsx
- apps/web/src/component/common/LocalNavigationBar/Navigation/space/SpaceItem.tsx
- apps/web/src/component/common/LocalNavigationBar/Navigation/space/SpacesList.tsx
- apps/web/src/component/retrospect/space/CompletedRetrospects.tsx
- apps/web/src/component/retrospect/space/InProgressRetrospects.tsx
- apps/web/src/component/retrospect/space/RetrospectSpaceHeader.tsx
- apps/web/src/router/index.tsx
- apps/web/src/style/designTokens.ts
> ### 회고 분석 페이지 추가 및 목록 표시 기능 개선
---
- 회고 완료 시 진입하는 페이지 컴포넌트를 추가하고, 회고 목록을 확인할 수 있는 컴포넌트를 분리하는 작업을 진행했습니다.
- 회고 완료 페이지 관련 신규 컴포넌트를 추가했습니다.
- 회고 완료 후 해당 페이지로 이동하도록 네비게이션 로직을 적용했습니다.
- 스페이스에서 실제 데이터를 불러오도록 요청 로직을 적용했습니다.
- 관련 컴포넌트들의 스타일링을 개선했습니다.
- close #522
> feat: 회고 분석 페이지 세팅

- apps/web/src/app/desktop/component/analysis/AnalysisDialog/AnalysisContent.tsx
- apps/web/src/app/desktop/component/analysis/AnalysisDialog/AnalysisIndividualTab.tsx
- apps/web/src/app/desktop/component/analysis/AnalysisDialog/AnalysisQuestionsTab.tsx
- apps/web/src/app/desktop/component/analysis/AnalysisDialog/index.tsx
- apps/web/src/app/desktop/component/home/RetrospectCard/index.tsx
- apps/web/src/app/desktop/retrospect/AnalysisPage.tsx
- apps/web/src/component/write/template/complete/ResultContainer.tsx
> ### 회고 분석 다이얼로그 개별 탭 작업
---
- 회고 분석 다이얼로그에 개별 분석 UI를 구현하고, 관련 API를 연동했습니다.
- 개별 질문을 위한 UI 컴포넌트를 구현하고, 필요한 API를 연동했습니다.
- `ResultContainer`에서 `name`과 `question` 유무에 따라 다른 스타일링을 적용(데스크톱 한정)하도록 했습니다.
- close #531
> feat: 회고 분석 다이얼로그 개별 탭 작업

- apps/web/src/app/desktop/component/analysis/AnalysisDialog/AnalysisContent.tsx
- apps/web/src/app/desktop/component/analysis/AnalysisDialog/AnalysisIndividualContents.tsx
- apps/web/src/app/desktop/component/analysis/AnalysisDialog/AnalysisTab.tsx
- apps/web/src/app/desktop/component/analysis/AnalysisDialog/AnalysisTeamContents.tsx
- apps/web/src/app/desktop/component/analysis/AnalysisDialog/RetrospectsOverview.tsx
- apps/web/src/app/desktop/component/home/RetrospectCard/index.tsx
- apps/web/src/component/retrospect/analysis/Analysis.tsx
- apps/web/src/component/retrospect/analysis/TeamSatisfactionChart.tsx
- apps/web/src/component/retrospect/space/CompletedRetrospects.tsx
- apps/web/src/component/retrospect/space/InProgressRetrospects.tsx
- apps/web/src/hooks/api/analysis/useApiGetAnalysis.ts
- apps/web/src/hooks/useSatisfactionData.ts
> ### 회고 분석 조회 api 연동
---
- 회고 분석 조회 API를 연동했습니다.
- 회고 분석 조회 API를 개인 / 팀에 맞게 적용했습니다.
- 완료된 회고만 다이얼로그가 뜨도록 수정했습니다.
- AI 분석중 컴포넌트 높이 조절을 했습니다.
- 개인의 일부는 회고 분석 조회 API 응답에 추가로 필요한 데이터가 있어서 백엔드 개발자분께 요청을 드렸습니다.
- 추가로 스페이스의 인원이 1명인 경우에는 #548 이슈에서 추가적인 퍼블리싱이 필요하여 해당 작업을 완료하면,
스페이스의 인원이 1명인 경우에도 화면에 표기가 될 것 같습니다.
https://github.com/user-attachments/assets/d8d6e51b-f820-4017-8d70-ee5fd469b07c
> feat: 회고 분석 api 연동
